<a href="https://colab.research.google.com/github/plopezmp/AmI/blob/main/AmI_Numpy%26Pandas_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

## Crear arrays

Lo podemos hacer con `np.array`

In [2]:
# como una lista
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
# como una matriz
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


Podemos crear arrays de ceros con `np.zeros` o con unos con `np.ones`.

## Crear arrays con un rango de números

In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


Comprobamos que no incluye el 12 en la lista

## Crear arrays con números aleatorios

In [6]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[59 74 53 92 91 90]


También podemos crear una lista de numeros aleatorios entre 0 y 1.

In [7]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.40734655 0.66433683 0.7506517  0.15778747 0.51592301 0.5841229 ]


## Broadcasting para realizar operaciones algebráicas con operandos de dimensiones diferentes

In [8]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.40734655 2.66433683 2.7506517  2.15778747 2.51592301 2.5841229 ]


In [9]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[177 222 159 276 273 270]


## EJERCICIO 1: Crear un dataset sencillo
El objetivo es crear un dataset de una sóla feature y una etiqueta, de la siguiente forma:
1. Crear un `np.array` de enteros entre 6 y 20 (incluido) de nombre `feature`
2. Asignar 15 valores a otro `np.array` de nombre `label`

`label = (3)(feature) + 4`

así, por ejemplo, el primer valor debería ser:

`label = (3)(6) + 4 = 22`

### Solución a la EJERCICIO 1:

In [ ]:
feature = ? # escriba aquí
print(feature)
label = ?   # escriba aquí
print(label)

In [ ]:
#@title click aquí para ver la solución
feature = np.arange(6, 21)
print (feature)
label = (feature * 3) + 4
print(label)

## EJERCICIO 2: Añadir ruido a el dataset
Para hacer que los datos sean más realistas podemos añadir un pequeño valor aleatorio a cada elemento del array `label`.

En concreto,  añadamos un número aleatorio tipo float cogidos entre -2 y +2. No ralice *broadcasting*, debe hacer un nuevo array `noise` que tenga las mismas dimensiones que `label``, es decir, 15 elementos


### Solución a la EJERCICIO 2:

In [ ]:
noise = ?    # escriba aquí
print(noise)
label = ?    # escriba aquí
print(label)

In [ ]:
#@title click aquí para ver la solución
noise = (np. random. random ( [15]) * 4)- 2
print (noise)
label = label + noise
print(label)

***

# PANDAS

Esta librería de Python introduce los **DataFrames** que se maneja de forma similar a las hojas de cálculo, de hecho:
* Un DataFrame almacena datos en celdas
* Un DataFrame pueden tener columnas con nombres y las filas están numeradas

In [12]:
import numpy as np
import pandas as pd

## Crear un DataFrame

El siguiente código crea un DataFrame de 10 celdas organizadas con:
* 5 filas
* 2 columnas, una de nombre `temperature` y otra `activity`

El código instancia una clase `pd.DataFrame` para generar un DataFrame. La clase toma 2 argumentos:
* El primero proporciona los datos para rellenar las 10 celdas. Lo hace usando `np.array` para generar un array de 5x2
* El segundo identifica los nombres de las dos columnas

In [ ]:
# Crear 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Crear una lista de nombres para las dos columnas.
my_column_names = ['temperature', 'activity']

# Crear DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Imprimir el DataFrame
print(my_dataframe)

## Añadir una columna nueva al DataFrame
la columna se llamará `adjusted`

In [ ]:
# Crar la columna adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Imprimir el dataframe
print(my_dataframe)

## Seleccionar un subconjunto de un DataFrame

In [ ]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

## EJERCICIO 3: Crear un DataFrame
Realice lo siguiente:
1. Cree un DataFrame de nombre `df` de 3x4 ( 3 filas x 4 columnas), con nombre de columnas `Elena, Carlos, Tomas, Juan`. Rellene el dataframe con números enteros aleatorios entre 0 y 100 (inclusive)
2. Muestre/Imprima:

  - El DataFrame
  - El valor de la celda de fila #1 y columna `Elena``

3. Cree una quinta columna de nombre `Juana` que tenga la suma de los valores de Tomas y Juan



### Solución a la EJERCICIO 3:

In [14]:
# Escriba su código aquí:



In [ ]:
#@title click aquí para ver la solución
my_column_names = ['Elena','Carlos','Tomas','Juan' ]
# Crear a 3x4 numpy array, cada celda con un num aleatorio
my_data= np.random. randint (low=0, high=101, size=(3, 4) )
# Crear a DataFrame.
df = pd.DataFrame (data=my_data, columns=my_column_names)
# Imprimir el DataFrame
print (df)
# Imprimir la fila #1 de la columna Elena.
print("Segunda fila de la columna Elena: %d\n" % df['Elena'][1])
# Cree una quinta columna de nombre Juana que tenga la suma de los
#valores de Tomas y Juan
df['Juana'] = df['Tomas'] + df['Juan']
# Imprimir el DataFrame construido
print (df)

## Copiar un DataFrame (opcional)

Hay dos formas:

* **Referenciar:** consiste asisnar el DataFrame a otro nombre/variable y cualquier cambio se verá reflejado en cualquiera de los dos nombres del DataFrame.
* **Copia:** se realiza con el método `pd.DataFrame.copy` y crea una copia independiente del DataFrame.

In [ ]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Juan'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Juan'][1])

# Modify a cell in df.
df.at[1, ''] = df['Juan'][1] + 5
print("  Updated df: %d" % df['Juan'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Juan'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])